[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "hardware-support",
    "embedded",
    "no-std",
]
description = "Board support crate for the BBC Micro:bit"
documentation = "https://docs.rs/microbit"
keywords = [
    "arm",
    "cortex-m",
    "nrf51",
]
license = "0BSD"
name = "microbit"
repository = "https://github.com/therealprof/microbit"
version = "0.4.3"

[dependencies]
cortex-m = "0.4.3"
cortex-m-rt = "0.4.0"
mag3110 = "0.1.2"
nb = "0.1.1"
numtoa = "0.0.7"
panic-abort = "0.1.1"
static-ref = "0.2.1"
vcell = "0.1.0"
volatile-register = "0.2.0"

[dependencies.nrf51-hal]
features = ["rt"]
version = "0.4.5"

[dependencies.rand]
default-features = false
version = "0.4.2"

[features]
default = ["rt"]
rt = []
[profile.dev]
debug = true
lto = true

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"
